### ISSUE TITLE
Presto support for M1

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#18031]
Running PrestoServer or HiveQueryRunner on macOS with M1 chip gives the following errors:
```
-12T20:14:49.742-0500	ERROR	main	Bootstrap	Uncaught exception in thread main
java.lang.RuntimeException: failed to load Hadoop native library
	at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:58)
	at com.facebook.presto.hive.HdfsEnvironment.<init>(HdfsEnvironment.java:52)
	at com.facebook.presto.hive.HiveQueryRunner.getFileHiveMetastore(HiveQueryRunner.java:265)
	at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:180)
	at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:137)
	at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:111)
	at com.facebook.presto.hive.HiveQueryRunner.main(HiveQueryRunner.java:428)
Caused by: java.lang.RuntimeException: library not found: /nativelib/Mac_OS_X-aarch64/libhadoop.dylib
	at com.facebook.presto.hadoop.HadoopNative.loadLibrary(HadoopNative.java:88)
	at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:47)
```

**Comment by 24601** [comment]
There are *lots* of discussions about this issue specifically (Apple M1/M2 SoCs, but specifically Hadoop native libs):

https://github.com/prestodb/presto/issues/17200
https://github.com/prestodb/presto/issues/15989


There are reports of bypassing this issue by using an x86 JDK (via Rosetta) so that you can then get around the Hadoop 3 aarch64 issue that is sticking point here, but it won't be at native speeds, but it'll probably still be pretty good.

**Comment by yingsu00** [comment]
Resolved

**Comment by Akanksha-kedia** [comment]
i m still facing issue chip : Apple M1 Pro but issue :
java.lang.ExceptionInInitializerError
	at io.prestosql.plugin.hive.HdfsEnvironment$$FastClassByGuice$$2c8553d4.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
	at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:117)
	at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.prestosql.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:63)
	at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:353)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:212)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:204)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:190)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.prestosql.server.Server.doStart(Server.java:119)
	at io.prestosql.server.Server.lambda$start$0(Server.java:73)
	at io.prestosql.$gen.Presto_unknown____20240504_042839_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:73)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
Caused by: java.lang.RuntimeException: failed to load Hadoop native library
	at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:59)
	at io.prestosql.plugin.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:39)
	... 52 more
Caused by: java.lang.RuntimeException: library not found: /nativelib/Mac_OS_X-aarch64/libhadoop.dylib
	at io.prestosql.hadoop.HadoopNative.loadLibrary(HadoopNative.java:89)
	at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:47)
	... 53 more
	
<img width="1017" alt="Screenshot 2024-05-04 at 10 01 10 AM" src="https://github.com/prestodb/presto/assets/89628774/1ae0faa1-651b-4322-85a8-fea390b5e776">

also i tried exporting  export DYLD_LIBRARY_PATH=/path/
