### ISSUE TITLE
After a Presto transaction is rollback successfully, new insert operations will fail

### ISSUE THREAD

**Issue by linghengqian** [prestodb/presto#25204]
## Your Environment

* Presto version used: `0.292`
* Storage (HDFS/S3/GCS..): `local filesystem directory as a Hive Metastore`
* Data source and connector used: `Iceberg Connector` with `iceberg.catalog.type=hive`
* Deployment (Cloud or On-prem): `On-prem`
* [Pastebin](https://pastebin.com/) link to the complete debug logs: https://pastebin.com/RSwgQzCG

## Expected Behavior

- After Presto successfully rollback a transaction, new insert operations should succeed.

## Current Behavior

- After a Presto transaction is rollback successfully, new insert operations will fail.

## Possible Solution

- Not sure yet.

## Steps to Reproduce

- I created a minimal reproducible unit test, `com.github.linghengqian.PrestoTest`, at https://github.com/linghengqian/presto-local-transaction-test .
- Execute the following PowerShell 7 command on the `Windows 11 Home 24H2` instance with `PowerShell/PowerShell`,
  `version-fox/vfox`, `git-for-windows/git` and `rancher-sandbox/rancher-desktop` installed.

```shell
vfox add java
vfox install java@21.0.7-ms
vfox use --global java@21.0.7-ms

git clone git@github.com:linghengqian/presto-local-transaction-test.git
cd ./presto-local-transaction-test/
./mvnw clean test -T 1C
```

## Screenshots (if appropriate)

- It doesn't seem necessary.

## Context

- This was discovered from the unit tests on the https://github.com/apache/shardingsphere/pull/35504 side.
- This is kind of like the unfocused point of https://github.com/prestodb/presto/issues/15916 .

**Comment by hantangwangd** [comment]
Hi @linghengqian, I think this issue has been fixed through PR #23247, however, it was not included in version 0.292. As I see, it was included since version release-0.293-edge4 and later.

**Comment by hantangwangd** [comment]
I think it's OK to keep this issue open until you confirm the fix after 0.293 is released.

**Comment by linghengqian** [comment]
> I think it's OK to keep this issue open until you confirm the fix after 0.293 is released.

- According to my test results at https://github.com/linghengqian/presto-local-transaction-test/commit/57cc6479981f2db658784c6440d932c417fbcdb4 , this problem still exists in Presto Server 0.293 and Presto JDBC Driver 0.293.

**Comment by hantangwangd** [comment]
Oh, sorry for misunderstanding the problem, I thought you were encountering the scenario where failed writes corrupted the entire transaction and connection, so that new insert operations couldn't succeed.

After checking the test case you provided in detail, I think the key point is that we haven't supported executing multiple write operations in a single transaction in Iceberg, that is to say, the fail insertion is caused by the following exception:

```
Catalog iceberg only supports writes using autocommit
```

This seems to be a current limitation, not a bug. Your test case will only succeed after we add support for multi-statement transactions in future.

Please let me know if this answers your question.

**Comment by linghengqian** [comment]
> Please let me know if this answers your question.
 
- Thanks for the wonderful explanation, I realized the problem started from the step of executing `conn.setAutoCommit(false)`.

> Your test case will only succeed after we add support for multi-statement transactions in future.

-  I wonder if the `future` you are referring to is https://github.com/prestodb/presto/pull/24986 ?

**Comment by hantangwangd** [comment]
That was a stale PR and would be closed soon. The updated PR is #25003, and I'm trying to push it forward.

For reference, the Iceberg community's design regarding isolation levels can be found at: https://docs.google.com/document/d/1UxXifU8iqP_byaW4E2RuKZx1nobxmAvc5urVcWas1B8/edit?tab=t.0

**Comment by hantangwangd** [comment]
Correction: the document is here: https://docs.google.com/document/d/1UxXifU8iqP_byaW4E2RuKZx1nobxmAvc5urVcWas1B8/edit?tab=t.0

**Comment by linghengqian** [comment]
Thank you for your clarification. I will close the current issue.

**Comment by linghengqian** [comment]
Since https://github.com/prestodb/presto/pull/25003 has just been merged, presto 0.297 should show that the current issue has been fixed.

**Comment by hantangwangd** [comment]
Yes, I believe so. Thanks so much for your continued attention on this.
