### ISSUE TITLE
Unable to Run SELECT Queries via Delta Lake Catalog with Kerberos HDFS

### ISSUE THREAD

**Issue by sharmvin26** [prestodb/presto#25912]
The SELECT query using the Delta Lake catalog with Kerberos-secured HDFS is failing, although I can list schemas and tables successfully. 
In contrast, the Hive catalog works as expected, I'm able to create tables and run SELECT queries without issues.

## Your Environment

* Presto version used: 0.293
* Storage (HDFS/S3/GCS..): Kerberized HDFS
* Data source and connector used: delta
* Deployment (Cloud or On-prem): docker with image prestodb/presto:0.293 and hdfs image prestodb/hdp2.6-hive-kerberized:10
* link to the complete logs: https://prestodb.slack.com/files/U09BZ7LQZLZ/F09CAS6090T/logs_from_the_start_of_the_query_

## Expected Behavior

Presto should return the contents of the table

## Steps to Reproduce

1.Have an on-prem Hadoop cluster with Kerberos authentication
2.Create Hive and Delta Lake connectors as shown below
3.Create a Delta Lake table on the cluster
4.Try querying the created table

## Context

hive.properties:
```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hadoop-master:9083

hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/hadoop-master@LABS.TERADATA.COM
hive.metastore.client.principal=hive/hadoop-master@LABS.TERADATA.COM
hive.metastore.client.keytab=/opt/presto-server/etc/catalog/hive.keytab

hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.keytab=/opt/presto-server/etc/catalog/hdfs.keytab
hive.hdfs.presto.principal=hdfs/hadoop-master@LABS.TERADATA.COM
```

delta.properties:
```
connector.name=delta
hive.metastore.uri=thrift://hadoop-master:9083
hive.config.resources=/opt/presto-server/etc/catalog/deltakerb/core-site.xml,/opt/presto-server/etc/catalog/deltakerb/hdfs-site.xml
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/hadoop-master@LABS.TERADATA.COM
hive.metastore.client.principal=hive/hadoop-master@LABS.TERADATA.COM
hive.metastore.client.keytab=/opt/presto-server/etc/catalog/hive.keytab

hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.keytab=/opt/presto-server/etc/catalog/hdfs.keytab
hive.hdfs.presto.principal=hdfs/hadoop-master@LABS.TERADATA.COM
```
krb5.conf:
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = LABS.TERADATA.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 LABS.TERADATA.COM = {
  kdc = hadoop-master:88
  admin_server = hadoop-master
 }
 OTHERLABS.TERADATA.COM = {
  kdc = hadoop-master:89
  admin_server = hadoop-master
 }
```

Query:
```
presto> select * from delta.default.trino_nation_delta_1;
Query 20250828_102415_00002_c6mgn failed: Failed to list the files in delta log

```
Error Logs:
```2025-08-28T10:24:16.076Z	WARN	Query-20250828_102415_00002_c6mgn-218	org.apache.hadoop.ipc.Client	Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
2025-08-28T10:24:16.078Z	WARN	Query-20250828_102415_00002_c6mgn-218	io.delta.kernel.internal.checkpoints.Checkpointer	Failed to load checkpoint metadata from file hdfs://hadoop-master:9000/user/hive/warehouse/trino_nation_delta_1-be8e127ddc494bb4a52628b8115855bf/_delta_log/_last_checkpoint. Retrying after 1sec. (current attempt = 0)
java.lang.RuntimeException: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "presto/172.20.0.4"; destination host is: "hadoop-master":9000;
	at io.delta.kernel.defaults.engine.DefaultJsonHandler$1.hasNext(DefaultJsonHandler.java:130)
	at io.delta.kernel.internal.util.InternalUtils.getSingularRow(InternalUtils.java:57)
	at io.delta.kernel.internal.checkpoints.Checkpointer.loadMetadataFromFile(Checkpointer.java:229)
	at io.delta.kernel.internal.checkpoints.Checkpointer.readLastCheckpointFile(Checkpointer.java:185)
	at io.delta.kernel.internal.snapshot.SnapshotManager.getSnapshotAtInit(SnapshotManager.java:346)
	at io.delta.kernel.internal.snapshot.SnapshotManager.buildLatestSnapshot(SnapshotManager.java:113)
	at io.delta.kernel.internal.TableImpl.getLatestSnapshot(TableImpl.java:55)
	at com.facebook.presto.delta.DeltaClient.getSnapshot(DeltaClient.java:123)
	at com.facebook.presto.delta.DeltaClient.getTable(DeltaClient.java:92)
	at com.facebook.presto.delta.DeltaMetadata.getTableHandle(DeltaMetadata.java:221)
	at com.facebook.presto.delta.DeltaMetadata.getTableHandle(DeltaMetadata.java:73)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:230)
	at com.facebook.presto.metadata.MetadataUtil.lambda$getOptionalTableHandle$7(MetadataUtil.java:202)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.facebook.presto.metadata.MetadataUtil.getOptionalTableHandle(MetadataUtil.java:202)
	at com.facebook.presto.metadata.MetadataManager$1.getTableHandle(MetadataManager.java:1400)
	at com.facebook.presto.util.MetadataUtils.lambda$getTableColumnMetadata$2(MetadataUtils.java:83)
	at com.facebook.presto.common.RuntimeStats.recordWallTime(RuntimeStats.java:140)
	at com.facebook.presto.util.MetadataUtils.getTableColumnMetadata(MetadataUtils.java:81)
	at com.facebook.presto.util.MetadataUtils.getTableColumnsMetadata(MetadataUtils.java:54)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1369)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:367)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:60)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:381)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2850)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1788)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:367)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:381)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:389)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1203)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:367)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:381)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:359)
	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:121)
	at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:95)
	at com.facebook.presto.execution.SqlQueryExecution.lambda$new$0(SqlQueryExecution.java:218)
	at com.facebook.presto.common.RuntimeStats.recordWallAndCpuTime(RuntimeStats.java:158)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:218)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:111)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:1009)
	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:170)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "presto/172.20.0.4"; destination host is: "hadoop-master":9000;
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy312.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy313.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
	at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
	at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
	at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
	at org.apache.hadoop.fs.HadoopExtendedFileSystem.open(HadoopExtendedFileSystem.java:134)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at io.delta.kernel.defaults.engine.DefaultJsonHandler$1.tryOpenNextFile(DefaultJsonHandler.java:165)
	at io.delta.kernel.defaults.engine.DefaultJsonHandler$1.hasNext(DefaultJsonHandler.java:124)
	... 51 more
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 77 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at jdk.security.jgss/com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:222)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:414)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 80 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at java.security.jgss/sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:162)
	at java.security.jgss/sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:126)
	at java.security.jgss/sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:193)
	at java.security.jgss/sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:218)
	at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:230)
	at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:196)
	at jdk.security.jgss/com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:203)
	... 89 more```

**Comment by imjalpreet** [comment]
@sharmvin26, can you please try the above test with the latest version of Presto, i.e., 0.294? There was an [issue](https://github.com/prestodb/presto/issues/25404) we fixed as part of the latest release, and based on my glance at the code, I feel your issue might be related and is failing due to the same reason. Let us know if you still have the issue, and we can look into it further.

**Comment by imjalpreet** [comment]
@sharmvin26 forgot to mention, if you would like to try on 0.293 itself, you could add this configuration to your catalog: `hive.copy-on-first-write-configuration-enabled=false`

**Comment by sharmvin26** [comment]
@imjalpreet I'm still encountering the same issues with Presto version 0.294, and also with the setting `hive.copy-on-first-write-configuration-enabled=false` on both the latest version and 0.293.
