### ISSUE TITLE
Queries with complex and many stages result in "unable to create new native thread" 

### ISSUE THREAD

**Issue by RobinUS2** [prestodb/presto#3434]
It looks like that there's too much of new threads spawned instantly once a very complex query is started. It feels to me that Presto shouldn't crash under whatever query, so we can make it reliable and robust to whatever someone inputs. 

The cluster become unresponsive after such a query, with new queries hanging in QUEUED state. We haven't seen it recover from this automatically.

Possible solution would be to limit the amount of threads, which currently doesn't seem the case. 

```
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method)
    at java.lang.Thread.start(Thread.java:714)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at com.facebook.presto.execution.SqlStageExecution.scheduleStartTasks(SqlStageExecution.java:401)
    at com.facebook.presto.execution.SqlStageExecution$$Lambda$371/1864740512.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.facebook.presto.execution.SqlStageExecution.scheduleStartTasks(SqlStageExecution.java:400)
    at com.facebook.presto.execution.SqlStageExecution$$Lambda$371/1864740512.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.facebook.presto.execution.SqlStageExecution.scheduleStartTasks(SqlStageExecution.java:400)
    at com.facebook.presto.execution.SqlStageExecution$$Lambda$371/1864740512.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.facebook.presto.execution.SqlStageExecution.scheduleStartTasks(SqlStageExecution.java:400)
    at com.facebook.presto.execution.SqlStageExecution.start(SqlStageExecution.java:392)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:216)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$85(QueuedExecution.java:68)
    at com.facebook.presto.execution.QueuedExecution$$Lambda$230/808613438.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Version 0.114

**Comment by cberner** [comment]
Do you have an example query that reproduces this on, say tpch data? I've never seen this

**Comment by RobinUS2** [comment]
Essentially it's a query consisting of about 700 different (problem seems to relate a bit to what happens   #3431 ) stages, which all seem to start a new thread (or multiple).

We have 24GB of RAM allocated per node.

**Comment by cberner** [comment]
Ah, I think that's an issue with how the scheduler currently works. Can you try https://github.com/facebook/presto/pull/3016 and see if that fixes it?

**Comment by dain** [comment]
The phased execution policy in that patch should fix the problem with everything stating at once, but I would expect that you will run into other problems with having 700 stages.  If it does work, I would love to know.

To enable the phased execution policy set the session property “execution_policy = ‘phased’” or set the configuration parameter "query.execution-policy = phased”.

-dain

**Comment by RobinUS2** [comment]
@cberner @dain  That sounds like something that would improve this indeed. Thanks for thinking with me. I will have to find some time to build from that branch, setup a test cluster and run the queries, which might take a few days.

**Comment by KBP-TDC** [comment]
@RobinUS2 could you please close the issue now? Unless the problem is not solved and you can share further insights.

**Comment by KBP-TDC** [comment]
FYI, we found that adding the following lines to the `/etc/security/limits.conf` file on all Presto nodes:
```
presto    soft    nproc 32768
presto    hard    nproc    65536
presto soft nofile 32768
presto hard nofile 65536
```
helped with similar issues.
