### ISSUE TITLE
Worker instance randomly exit during queries

### ISSUE THREAD

**Issue by tesseract2048** [prestodb/presto#5664]
Hi there. After updated to 0.150, I experienced a strange issue that worker randomly exit during queries (especially when multiple queries are running concurrently).

The following is last logs from a exited work:

```
Jul 14, 2016 5:36:13 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 32068 records.
Jul 14, 2016 5:36:13 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
Jul 14, 2016 5:36:13 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 11 ms. row count = 32068
Jul 14, 2016 5:36:27 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAtt
2016-07-14T17:36:41.603+0800    ERROR   exchange-client-22      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.6.128.138:8088/v1/task/20160714_093641_00028_e4m62.2.19/results/20160714_093641_00028_
e4m62.1.41 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:36:41.612+0800    ERROR   exchange-client-0       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.6.194.14:8088/v1/task/20160714_093641_00028_e4m62.2.28/results/20160714_093641_00028_e
4m62.1.41 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:36:41.612+0800    ERROR   exchange-client-0       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.6.130.223:8088/v1/task/20160714_093641_00028_e4m62.2.70/results/20160714_093641_00028_
e4m62.1.41 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:36:41.613+0800    ERROR   exchange-client-0       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.6.131.39:8088/v1/task/20160714_093641_00028_e4m62.2.21/results/20160714_093641_00028_e
4m62.1.41 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:36:41.927+0800    ERROR   exchange-client-4       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.6.130.163:8088/v1/task/20160714_093641_00028_e4m62.3.9/results/20160714_093641_00028_e
4m62.2.41 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:36:42.126+0800    ERROR   SplitRunner-7-43        com.facebook.presto.execution.TaskExecutor      Error processing Split 20160714_093641_00028_e4m62.3.43-1 {path=hdfs://hive_table0/date=20160608/hour=00/part-r-00006-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet, start=1073741824, length=67108864, hosts=[n6-194-147.byted.org, n6-128-139.byted.org, n6-128-131.byted.org], database=default, table=fact_sns
sdk_nginx_log_daily, forceLocalScheduling=false, partitionName=date=20160608/hour=00, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@41c917b9} (start = 1468489001523, wall = 603 ms, cpu = 0 ms, calls = 1): HIVE_CANNO
T_OPEN_SPLIT: Error opening Hive split hdfs://hive_table0/date=20160608/hour=00/part-r-00006-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet (offset=1073741824, length=67108864): null
2016-07-14T17:36:42.152+0800    ERROR   SplitRunner-1-37        com.facebook.presto.execution.TaskExecutor      Error processing Split 20160714_093641_00028_e4m62.3.43-2 {path=hdfs://hive_table0/date=20160608/hour=00/part-r-00022-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet, start=1946157056, length=67108864, hosts=[n6-195-018.byted.org, n6-130-142.byted.org, n6-130-149.byted.org], database=default, table=fact_sns
sdk_nginx_log_daily, forceLocalScheduling=false, partitionName=date=20160608/hour=00, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@41c917b9} (start = 1468489001523, wall = 629 ms, cpu = 0 ms, calls = 1): HIVE_CANNO
T_OPEN_SPLIT: Error opening Hive split hdfs://hive_table0/date=20160608/hour=00/part-r-00022-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet (offset=1946157056, length=67108864): null
2016-07-14T17:36:42.161+0800    ERROR   SplitRunner-3-39        com.facebook.presto.execution.TaskExecutor      Error processing Split 20160714_093641_00028_e4m62.3.43-3 {path=hdfs://hive_table0/date=20160608/hour=00/part-r-00005-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet, start=939524096, length=67108864, hosts=[n6-128-212.byted.org, n6-128-205.byted.org, n6-194-229.byted.org], database=default, table=fact_snss
dk_nginx_log_daily, forceLocalScheduling=false, partitionName=date=20160608/hour=00, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@41c917b9} (start = 1468489001523, wall = 638 ms, cpu = 0 ms, calls = 1): HIVE_CANNOT
_OPEN_SPLIT: Error opening Hive split hdfs://hive_table0/date=20160608/hour=00/part-r-00005-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet (offset=939524096, length=67108864): null
2016-07-14T17:36:42.164+0800    ERROR   SplitRunner-6-42        com.facebook.presto.execution.TaskExecutor      Error processing Split 20160714_093641_00028_e4m62.3.43-6 {path=hdfs://hive_table0/date=20160608/hour=00/part-r-00001-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet, start=1308622848, length=33554432, hosts=[n6-130-203.byted.org, n6-194-029.byted.org, n6-130-195.byted.org], database=default, table=fact_sns
sdk_nginx_log_daily, forceLocalScheduling=false, partitionName=date=20160608/hour=00, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@41c917b9} (start = 1468489001538, wall = 626 ms, cpu = 0 ms, calls = 1): HIVE_CANNO
T_OPEN_SPLIT: Error opening Hive split hdfs://hive_table0/date=20160608/hour=00/part-r-00001-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet (offset=1308622848, length=33554432): Failed 
on local exception: java.nio.channels.ClosedByInterruptException; Host Details : local host is: "n6-194-081/10.6.194.81"; destination host is: "n6-195-031.byted.org":65212; 
2016-07-14T17:36:42.165+0800    ERROR   SplitRunner-5-41        com.facebook.presto.execution.TaskExecutor      Error processing Split 20160714_093641_00028_e4m62.3.43-5 {path=hdfs://hive_table0/date=20160608/hour=00/part-r-00002-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet, start=1476395008, length=33554432, hosts=[n6-130-143.byted.org, n6-131-050.byted.org, n6-130-144.byted.org], database=default, table=fact_sns
sdk_nginx_log_daily, forceLocalScheduling=false, partitionName=date=20160608/hour=00, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@41c917b9} (start = 1468489001538, wall = 627 ms, cpu = 0 ms, calls = 1): HIVE_CANNO
T_OPEN_SPLIT: Error opening Hive split hdfs://hive_table0/date=20160608/hour=00/part-r-00002-2f743039-717f-4798-8ef3-27a85a54323b.snappy.parquet (offset=1476395008, length=33554432): Failed 
on local exception: java.nio.channels.ClosedByInterruptException; Host Details : local host is: "n6-194-081/10.6.194.81"; destination host is: "n6-195-031.byted.org":65212; 
2016-07-14T17:37:42.899+0800    ERROR   exchange-client-7       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.3.128.162:8088/v1/task/20160714_093742_00031_e4m62.2.30/results/20160714_093742_00031_
e4m62.1.58 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-07-14T17:40:19.472+0800    ERROR   exchange-client-12      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://10.3.132.152:8088/v1/task/20160714_093917_00035_e4m62.2.74/results/20160714_093917_00035_e4m62.1.51 failed io.airlift.http.client.RuntimeIOException: java.net.SocketTimeoutException: Connect Timeout
Already running as 183625
2016-07-14T17:51:49.854+0800    INFO    Thread-22       io.airlift.bootstrap.LifeCycleManager   Life cycle stopping...
```

I've also examined other logs (http-request.log, for example), and there was nothing.

Any thoughts? Thanks.

**Comment by bdm123** [comment]
Seeing the same error in the workers log file when querying a bucketed hive table in s3.  Query will  just remain stuck after XX percent and never complete. Running Presto 0.150 on EMR. Any updates on this issue?

> 2016-11-02T20:31:25.683Z        INFO    20161102_203124_00014_b7ui2.2.2-13-35   com.amazonaws.latency   ServiceName=[Amazon S3], StatusCode=[206], ServiceEndpoint=
> [https://data123.s3.amazonaws.com], AWSRequestID=[80AD0892DEBE465E], HttpClientPoolPendingCount=7, HttpClientPoolAvailableCount=0, RequestCount=1, HttpClientPoolLeasedCount=500, ResponseProcessingTime=[0.056], ClientExecuteTime=[117.532], HttpClientSendRequestTime=[0.043], HttpRequestTime=[117.357], RequestSigningTime=[0.059], HttpClientReceiveResponseTime=[14.263],
> 2016-11-02T20:31:25.686Z        INFO    20161102_203124_00014_b7ui2.2.2-13-35   stdout  .InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:44 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 2880100 records.
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:44 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:45 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 2866041 records.
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:45 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:45 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:45 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:45 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:45 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 1336 ms. row count = 2866041
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 2610100 records.
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:46 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:46 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 181 ms. row count = 2610100
> Nov 2, 2016 8:30:46 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 2598983 records.
> Nov 2, 2016 8:30:46 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:47 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:47 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 191 ms. row count = 2598983
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 0 records.
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 715716 records.
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:47 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 2860100 records.
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 145 ms. row count = 2860100
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 3100100 records.
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 534 ms. row count = 715716
> Nov 2, 2016 8:30:47 PM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 246 ms. row count = 3100100
> Nov 2, 2016 8:31:25 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:31:25 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
> Nov 2, 2016 8:31:25 PM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a ins
> 2016-11-02T20:31:25.694Z        INFO    20161102_203124_00014_b7ui2.2.2-8-44    com.amazonaws.latency   ServiceName=[Amazon S3], StatusCode=[206], ServiceEndpoint=[https://data123.s3.amazonaws.com], AWSRequestID=[43A7A8D772381B74], HttpClientPoolPendingCount=7, HttpClientPoolAvailableCount=0, RequestCount=1, HttpClientPoolLeasedCount=500, ResponseProcessingTime=[0.014], ClientExecuteTime=[128.035], HttpClientSendRequestTime=[0.046], HttpRequestTime=[127.9], RequestSigningTime=[0.061], HttpClientReceiveResponseTime=[24.065],
>

**Comment by dain** [comment]
@tesseract2048 given that you are getting "Life cycle stopping..." in the logs that normally mean someone called `System.exit` or a sig quit was sent to the process.  When there is a hard crash, the VM just exits and you normally get an hprof file.

@bdm123 your post log doesn't seem related since you are seeing a "hang".  There are many reasons for a query to appear to "hang".  It can be as simple as a bad HDFS data node, or could be caused by running very very low on memory so you get stuck in GC loops (if the system is configured incorrectly), or the most common case is a bad query with either massive skew crazy joins (saw one yesterday internally where 10k rows generated 10B output rows).  You have to dig into the system and see what the root cause is.

**Comment by bdm123** [comment]
Thanks @dain dain - Digging into my issue further I found that S3 connections are timing out (log error below).  I'm querying 20GB (479 files) parquet table with 10 nodes * 8GB memory. Query is a sum/where/group by and should be reasonable amount of resources.  Any idea why S3/presto is 'choking'?

> 2016-11-03T18:00:26.916Z        INFO    20161103_172826_00008_b7ui2.2.8-27-48   com.amazonaws.http.AmazonHttpClient Unable to execute HTTP request: Timeout waiting for 
connection from pool
> org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
>         at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
>         at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
>         at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
>         at com.amazonaws.http.conn.$Proxy164.getConnection(Unknown Source)
>         at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
>         at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
>         at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:706)
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3674)
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1160)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.lambda$openStream$1(PrestoS3FileSystem.java:836)
>         at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:136)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.openStream(PrestoS3FileSystem.java:833)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.openStream(PrestoS3FileSystem.java:818)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.seekStream(PrestoS3FileSystem.java:811)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.lambda$read$0(PrestoS3FileSystem.java:750)
>         at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:136)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.read(PrestoS3FileSystem.java:749)
>         at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
>         at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
>         at java.io.FilterInputStream.read(FilterInputStream.java:83)
>         at com.facebook.presto.hive.parquet.reader.ParquetMetadataReader.readIntLittleEndian(ParquetMetadataReader.java:286)
>         at com.facebook.presto.hive.parquet.reader.ParquetMetadataReader.readFooter(ParquetMetadataReader.java:83)
>         at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:163)
>         at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:126)
>         at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:90)
>         at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
>         at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
>         at com.facebook.presto.operator.ScanFilterAndProjectOperator.createSourceIfNecessary(ScanFilterAndProjectOperator.java:292)
>         at com.facebook.presto.operator.ScanFilterAndProjectOperator.isFinished(ScanFilterAndProjectOperator.java:180)
>         at com.facebook.presto.operator.Driver.processInternal(Driver.java:375)
>         at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
>         at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
>         at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
>         at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> 
> 
> 2016-11-03T18:00:45.319Z        INFO    20161103_172650_00006_b7ui2.2.9-2-36    com.amazonaws.http.AmazonHttpClient Unable to execute HTTP request: Timeout waiting for connection from pool
> org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
>         at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
>         at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
>         at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
>         at com.amazonaws.http.conn.$Proxy164.getConnection(Unknown Source)
>         at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
>         at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
>         at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:706)
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3674)
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1160)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.lambda$openStream$1(PrestoS3FileSystem.java:836)
>         at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:136)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.openStream(PrestoS3FileSystem.java:833)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.openStream(PrestoS3FileSystem.java:818)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.seekStream(PrestoS3FileSystem.java:811)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.lambda$read$0(PrestoS3FileSystem.java:750)
>         at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:136)
>         at com.facebook.presto.hive.PrestoS3FileSystem$PrestoS3InputStream.read(PrestoS3FileSystem.java:749)
>         at org.apache.hadoop.fs.FSInputStream.read(FSInputStream.java:65)
>         at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:78)
>         at org.apache.hadoop.fs.BufferedFSInputStream.readFully(BufferedFSInputStream.java:113)
>         at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
>         at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:82)
>         at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readFully(HdfsParquetDataSource.java:74)
>         at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readFully(HdfsParquetDataSource.java:67)
>         at com.facebook.presto.hive.parquet.reader.ParquetReader.readBlock(ParquetReader.java:150)
>         at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:373)
>         at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:349)
>         at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:235)
>         at com.facebook.presto.spi.block.LazyBlock.isNull(LazyBlock.java:211)
>         at com_facebook_presto_$gen_PageProcessor_34.project_3(Unknown Source)
>         at com_facebook_presto_$gen_PageProcessor_34.process(Unknown Source)
>         at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:260)
>         at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
>         at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
>         at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
>         at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
>         at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> 
>

**Comment by nezihyigitbasi** [comment]
@bdm123 I think you are hitting the issue that I fixed in #5629 (released in 0.152, see release notes [here](https://prestodb.io/docs/current/release/release-0.152.html)). The bug leaks connections while talking to s3.

**Comment by bdm123** [comment]
Great. Thanks for the quick response @nezihyigitbasi! I will try to upgrade the cluster with the latest EMR release which has Presto 0.152.3 and let you know if I still have any issues.

**Comment by nezihyigitbasi** [comment]
BTW note that #5629 can explain why the connection pool run out of connections but it doesn't explain why your workers crash/exit, which is the very first issue you posted.

**Comment by bdm123** [comment]
Thanks so much again @nezihyigitbasi - I haven't been seeing the same connection pool error and getting better performance since upgrading to 0.152.3.  
Not as frequent but when running the same/similar queries over time they still occasionally get stuck.  For example, I run a query that normally takes ~2 minutes to complete a few dozen times (not concurrently) and then run the same or slightly modified query again and it hangs 10-30+ minutes before it completes. Several minutes later (if I cross my fingers) it runs again at 2 minutes. There is no other activity on this cluster (although I'm trying to bring this into a production environment with multiple users). 

I found "NO_MORE_BUFFERS" in one of the blocked tasks and no erros in the server.log.  Any ideas on this inconsistent query performance?

`"lastHeartbeat": "2016-11-14T05:41:52.306Z",
"outputBuffers": {
"type": "SHARED",
"state": "NO_MORE_BUFFERS",
"canAddBuffers": false,
"canAddPages": true,
"totalBufferedBytes": 0,
"totalBufferedPages": 0,
"totalRowsSent": 0,
"totalPagesSent": 0,
"buffers": [
{
"bufferId": 0,
"finished": false,
"bufferedPages": 0,
"pagesSent": 0,
"pageBufferInfo": {
"partition": 0,
"bufferedPages": 0,
"bufferedBytes": 0,
"rowsAdded": 0,
"pagesAdded": 0
}
}
]
},`

**Comment by nezihyigitbasi** [comment]
@bdm123 glad that it solved your problem.

I have seen a similar issue where the timeout/retry config for the s3 filesystem were high, which was causing the threads making s3 calls to block (& retry) for a long time when calls fail (and the user will see that the query just hangs).

What is your s3 timeout/retry related config? (`hive.s3.connect-timeout`, `hive.s3.socket-timeout`, `hive.s3.max-retry-time`, etc.)

**Comment by bdm123** [comment]
Hey @nezihyigitbasi - Below are my current settings (which in fact were borrowed from the netflix blog post on presto :) ). Anything you would recommend changing? 

hive.s3.connect-timeout=5m
hive.s3.max-backoff-time=10m
hive.s3.max-error-retries=50
hive.s3.max-connections=500
hive.s3.max-client-retries=50
hive.s3.socket-timeout=5m

**Comment by nezihyigitbasi** [comment]
That's probably the reason. I have significantly reduced these values after I started seeing similar issues that you describe (straggler tasks, heavy tails, etc.). Here is our current hive s3 config:

```
hive.s3.max-client-retries=25
hive.s3.max-error-retries=50
hive.s3.max-connections=500
hive.s3.connect-timeout=5s
hive.s3.socket-timeout=5s
hive.s3.max-backoff-time=10m
hive.s3.max-retry-time=10m
```

**Comment by bdm123** [comment]
I believe something magical just happened.  :)  I've been throwing many concurrent queries at presto and haven't gotten any of them to hang so far.  Will continue testing but this is game changer for sure in getting this into production.  A Megaton Thanks for your help and contributions @nezihyigitbasi !

**Comment by nezihyigitbasi** [comment]
@bdm123 something magical is probably the s3 backend :) Sometimes s3 throttles your requests or somehow you hit some "bad" machine in the backend and in those cases Presto threads will start failing & retrying to complete the s3 calls, and you will see the query hanging. I still recommend lowering the timeout values.

**Comment by martint** [comment]
>  have significantly reduced these values after I started seeing similar issues that you describe 

We should consider making those the defaults.

**Comment by nezihyigitbasi** [comment]
The [default timeouts](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveClientConfig.java#L92-L93) are already `5s` so we are good.

**Comment by bdm123** [comment]
Just to note the performance difference was after lowering the timeouts as you suggested.  Hmm, since those are already the defaults - maybe need an updated netflix blog post :) (as I think many people follow and reblog optimization advice from that rare and classic presto article).

**Comment by bdm123** [comment]
Btw - Is there any documentation on AWS S3's throttling process and ensuring it does not happen? Initially this was a hard suspicion of mine but I could not find much information on it or confirm whether it was happening.  I would think it was a more common concern as many are utilizing S3 in someway as a data storage layer.

**Comment by nezihyigitbasi** [comment]
I don't think there is much public info about the internals of how/when clients are throttled, the only documented fact is clients may get a 503 when they get throttled.

Btw it is not only about throttling, although throttling may cause stragglers I have also seen clients timing out (on read/connect) too (see the stack traces in your worker logs).

**Comment by nezihyigitbasi** [comment]
@bdm123 assuming your issue has been fixed, please re-open otherwise.

**Comment by hustnn** [comment]
Hi @nezihyigitbasi 

I also met this problem 
"DEBUG   page-buffer-client-callback-21  com.facebook.presto.operator.HttpPageBufferClient       Request to http://ipaddress:8000/v1/task/20180404_040947_00412_2rwvm.0.0/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled."

I am using presto 0.196. Thanks.

**Comment by EvilPuppetMaster** [comment]
This issue can also be resolved while remaining on EMRFS by setting `fs.s3.maxConnections` to something larger than the default 500 in `emrfs-site` config

https://aws.amazon.com/premiumsupport/knowledge-center/emr-timeout-connection-wait/
