### ISSUE TITLE
Filter based on VARCHAR literal padded with spaces returns wrong results

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#7550]
Based on *tpcds.sf10* data:

```sql
presto:sf10> select count(*) from item where i_category IN ('Sports                                            ');
 _col0
-------
 10287
(1 row)
```

vs

```sql
presto:sf10> select count(*) from item where i_category = 'Sports                                            ';
 _col0
-------
     0
(1 row)
```

The only difference is `IN` vs `=`.

Here are plans:

```sql
presto:sf10> explain select count(*) from item where i_category IN ('Sports                                            ');
                                                                                                                                                   Query Plan
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]
         _col0 := count
     - Aggregate(FINAL) => [count:bigint]
             count := "count"("count_3")
         - LocalExchange[SINGLE] () => count_3:bigint
             - RemoteExchange[GATHER] => count_3:bigint
                 - Aggregate(PARTIAL) => [count_3:bigint]
                         count_3 := "count"(*)
                     - ScanFilterProject[table = hive:hive:sf10:item, originalConstraint = (CAST("i_category" AS varchar(50)) IN ('Sports                                            ')), filterPredicate = (CAST("i_category" AS varchar(50)) IN ('Sports
                             LAYOUT: hive
                             i_category := HiveColumnHandle{clientId=hive, name=i_category, hiveType=char(50), hiveColumnIndex=12, columnType=REGULAR, comment=Optional.empty}

(1 row)
```

```sql
presto:sf10> explain select count(*) from item where i_category = 'Sports                                            ';
                                                                                                                                   Query Plan
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]
         _col0 := count
     - Aggregate(FINAL) => [count:bigint]
             count := "count"("count_3")
         - LocalExchange[SINGLE] () => count_3:bigint
             - RemoteExchange[GATHER] => count_3:bigint
                 - Aggregate(PARTIAL) => [count_3:bigint]
                         count_3 := "count"(*)
                     - ScanFilterProject[table = hive:hive:sf10:item, originalConstraint = (CAST("i_category" AS varchar(50)) = 'Sports                                            '), filterPredicate = ("i_category" = "$literal$char(50)"("from_base64"('U3BvcnRz')))] => []
                             LAYOUT: hive
                             i_category := HiveColumnHandle{clientId=hive, name=i_category, hiveType=char(50), hiveColumnIndex=12, columnType=REGULAR, comment=Optional.empty}

(1 row)
```

**Comment by cawallin** [comment]
Fixed by https://github.com/prestodb/presto/pull/7543

**Comment by maciejgrzybek** [comment]
Nope, it's not fixed. Still valid.
Most recent master (HEAD = 1f33a95dff5c2508fd772a82e8c10f9bea481601) gives:
```
presto:default> select count(*) from item where i_category IN ('Sports                                            ');
 _col0
-------
  1783
(1 row)
```

vs
```
presto:default> select count(*) from item where i_category = 'Sports                                            ';
 _col0
-------
     0
(1 row)
```

**Comment by maciejgrzybek** [comment]
Fixed.
```
presto:sf10> select count(*) from item where i_category IN ('Sports                                            ');
 _col0
-------
 10287
(1 row)
```

vs

```
presto:sf10> select count(*) from item where i_category = 'Sports                                            ';
 _col0
-------
 10287
(1 row)
```
