### ISSUE TITLE
Analysis error in query involving grouping() and implicit coercion

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8499]
```sql
SELECT
    1.0 * count(*),
    grouping(x)
FROM (VALUES 1) t(x)
GROUP BY GROUPING SETS ((x))
```

Fails with:

```
com.facebook.presto.sql.analyzer.SemanticException: Column 'x' cannot be resolved
        at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
        at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:371)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:282)
        at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:51)
        at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitGroupingOperation(ExpressionAnalyzer.java:1130)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitGroupingOperation(ExpressionAnalyzer.java:282)
        at com.facebook.presto.sql.tree.GroupingOperation.accept(GroupingOperation.java:49)
        at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1447)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1400)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1366)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1354)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1342)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:118)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
        at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
        at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
        at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
        at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
        at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
        at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
        at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
        at com.facebook.presto.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:57)
        at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:60)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
        at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:60)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:128)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:121)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

It doesn't happen if `1.0 *` is removed or `count(*)` is explicitly cast to double before multiplying it, which makes me think this is a issue with implicit coercions.

**Comment by martint** [comment]
cc @petroav, @sopel39

**Comment by petroav** [comment]
@martint thanks for the repro, I'll take a look.

**Comment by petroav** [comment]
Just tried the query and it works. I think it was fixed by https://github.com/prestodb/presto/pull/8739.

**Comment by martint** [comment]
This is still a problem when there's more than one grouping set:

```
SELECT
    1.0 * count(*),
    grouping(x)
FROM (VALUES 1) t(x)
GROUP BY GROUPING SETS ((x), ())
```
