### ISSUE TITLE
Leak tasks?

### ISSUE THREAD

**Issue by guangyy** [prestodb/presto#9530]
Presto version: 0.166

While looking at some stability issues, I found one Presto worker is being pulled for a task status of an old task (several days ago).

I was looking at the http-request logs of 12/11/2017, and I found:
```
guang_yang@i-06198abe7b0358cdd:~ presto-worker-prod-1-production $ grep "/v1/task/20171123_033327_72924_nraag.7.106/results/55/0" http-request.log | head
2017-12-10T23:59:59.958Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1103	null
2017-12-11T00:00:01.062Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1366	null
2017-12-11T00:00:02.429Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1612	null
2017-12-11T00:00:04.041Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1522	null
2017-12-11T00:00:05.563Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1425	null
2017-12-11T00:00:06.988Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1959	null
2017-12-11T00:00:08.947Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1455	null
2017-12-11T00:00:10.402Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1278	null
2017-12-11T00:00:11.680Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1653	null
2017-12-11T00:00:13.333Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1717	null
guang_yang@i-06198abe7b0358cdd:~ presto-worker-prod-1-production $ grep "/v1/task/20171123_033327_72924_nraag.7.106/results/55/0" http-request.log | tail
2017-12-11T19:05:36.447Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1110	null
2017-12-11T19:05:37.583Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1518	null
2017-12-11T19:05:39.146Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1332	null
2017-12-11T19:05:40.480Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1865	null
2017-12-11T19:05:42.352Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1349	null
2017-12-11T19:05:43.707Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1349	null
2017-12-11T19:05:45.057Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1615	null
2017-12-11T19:05:46.720Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1583	null
2017-12-11T19:05:48.305Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1708	null
2017-12-11T19:05:50.015Z	10.113.223.230	GET	/v1/task/20171123_033327_72924_nraag.7.106/results/55/0	null	null	204	0	0	1552	null
```

Looking at the timestamps of the request, it is being pulled until the worker get restarted. Some coordinator log at 11/23:
```
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:28.862Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.3 is SCHEDULING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.005Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.3 is SCHEDULED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.005Z DEBUG   query-execution-40551   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.3 is RUNNING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.005Z DEBUG   query-execution-40551   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.2 is SCHEDULING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.138Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.2 is SCHEDULED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.138Z DEBUG   query-execution-40549   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.2 is RUNNING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.139Z DEBUG   query-execution-40549   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.1 is SCHEDULING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.257Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.1 is SCHEDULED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.257Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.0 is SCHEDULING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.258Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.1 is RUNNING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.258Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.0 is SCHEDULED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:29.259Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.0 is RUNNING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:31.028Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.8 is SCHEDULED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:31.028Z DEBUG   query-execution-40570   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.8 is RUNNING
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-execution-40570   com.facebook.presto.execution.QueryStateMachine Query 20171123_033327_72924_nraag is FAILED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-management-4      com.facebook.presto.execution.QueryStateMachine Query 20171123_033327_72924_nraag failed
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-execution-40549   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.0 is ABORTED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-execution-40551   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.1 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-execution-40554   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.2 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.238Z DEBUG   query-execution-40565   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.3 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.241Z DEBUG   query-execution-40556   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.4 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.242Z DEBUG   query-execution-40558   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.5 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.242Z DEBUG   query-execution-40558   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.6 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.242Z DEBUG   query-execution-40544   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.7 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.278Z DEBUG   query-execution-40551   com.facebook.presto.execution.StageStateMachine Stage 20171123_033327_72924_nraag.8 is CANCELED
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:40.354Z DEBUG   exchange-client-15      com.facebook.presto.operator.HttpPageBufferClient       Request to http://10.71.203.204:5713/v1/task/20171123_033327_72924_nraag.0.0/results/0/0 failed java.util.concurrent.CancellationException: Task was cancelled.
server.log-2017-11-23.3.log.gz:2017-11-23T03:33:44.710Z INFO    query-execution-40570   com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171123_033327_72924_nraag :: Transaction:[797cbcae-7af1-4cea-8143-5f35df1e8b7a] :: elapsed 12401ms :: planning 848ms :: scheduling 38ms :: running 13137ms :: finishing 0ms :: begin 2017-11-23T03:33:27.836Z :: end 2017-11-23T03:33:40.237Z
server.log-2017-11-23.3.log.gz:2017-11-23T03:38:45.337Z DEBUG   query-management-1      com.facebook.presto.execution.SqlQueryManager   Remove query 20171123_033327_72924_nraag
```

Is this a known issue? Thanks!

**Comment by nezihyigitbasi** [comment]
Can you please try the latest version (v 0.190)? I remember something like this has been fixed long ago and you are using a pretty old release.

**Comment by guangyy** [comment]
Thanks for the reply! Yeah let me upgrade the cluster to see if it still happens.

**Comment by guangyy** [comment]
We have recently upgraded to 0.188 and still see the leak for tasks.

Are there any configuration to reclaim the tasks if they have been there for an extended period of time?

**Comment by guangyy** [comment]
![screen shot 2018-05-03 at 11 12 02 am](https://user-images.githubusercontent.com/891065/39594984-08278f22-4ec3-11e8-9a12-bb485c52e358.png)

**Comment by guangyy** [comment]
The above screenshot shows the tasking for a worker, we can see that there are lots of tasks are started several days ago. In our case, none of the queries execute longer than 1 hour.

**Comment by guangyy** [comment]
We are using the standard hive connector. Those tasks are being blocked. Sorry I restarted the cluster, but it is easy to reproduce, I will do a jstack next time seeing this.

Following is the pending splits before and after the restart:
![screen shot 2018-05-03 at 11 31 13 am](https://user-images.githubusercontent.com/891065/39608028-762ae9d0-4ef3-11e8-8b29-c4cb456bfb1e.png)

**Comment by guangyy** [comment]
From the jstack, I couldn't find the _leaked_ tasks, maybe because they are _blocked_ splits?

**Comment by guangyy** [comment]
>> Can you check the HTTP log on the worker to see if the coordinator is asking for status for the leaked tasks? If the coordinator is pinging the task then the problem is on the coordinator. If not, the problem is on the worker.

The request are from `coordinator`.

Also, what happens if you click on one of the "leaked queries" in the UI? Also, you should be able to see the task info by hitting "/v1/task?pretty" on the worker node.

```{                                                                                                                                                                                                                                                           
   "taskStatus" : {                                                                                                                                                                                                                                          
     "taskId" : "20180506_001247_00615_7psrs.33.9",                                                                                                                                                                                                          
     "taskInstanceId" : "b82069a9-69fd-477e-b9d5-a469dae027ea",                                                                                                                                                                                              
     "version" : 4096129,                                                                                                                                                                                                                                    
     "state" : "RUNNING",                                                                                                                                                                                                                                    
     "self" : "http://172.21.62.133:5797/v1/task/20180506_001247_00615_7psrs.33.9",                                                                                                                                                                          
     "nodeId" : "i-07908de3dcd480ee6",                                                                                                                                                                                                                       
     "failures" : [ ],                                                                                                                                                                                                                                       
     "queuedPartitionedDrivers" : 0,                                                                                                                                                                                                                         
     "runningPartitionedDrivers" : 0,                                                                                                                                                                                                                        
     "memoryReservation" : "0B"                                                                                                                                                                                                                              
   },                                                                                                                                                                                                                                                        
   "lastHeartbeat" : "2018-05-10T22:35:09.958Z",                                                                                                                                                                                                             
   "outputBuffers" : {                                                            ```

**Comment by guangyy** [comment]
[leaked_tast_pretty.txt](https://github.com/prestodb/presto/files/1993466/leaked_tast_pretty.txt)

The output while hitting `/v1/task?pretty` for the leaked task.

**Comment by haozhun** [comment]
A fix for a similar symptom is in 0.178: 4fa5a47af86c4da13977ac6432dc380e02772948

**Comment by guangyy** [comment]
If we look a the query status on the coordinator page `v1/query`, that query is already marked as failed ```{
queryId: "20180506_001247_00615_7psrs",
session: {
queryId: "20180506_001247_00615_7psrs",
transactionId: "0b38cd4b-9c72-4796-b645-d2a6c3b0a05b",
clientTransactionSupport: false,
user: "svc_di_data_products_infra",
source: "omniduct 0.5.2",
catalog: "silver",
schema: "default",
timeZoneKey: 0,
locale: "en_US",
remoteUserAddress: "127.0.0.1",
userAgent: "python-requests/2.18.4",
clientTags: [ ],
startTime: 1525565567792,
systemProperties: { },
catalogProperties: { },
preparedStatements: { }
},
state: "FAILED",
memoryPool: "general",```

**Comment by guangyy** [comment]
@haozhun , thanks for the reply! We are seeing this problem running 0.188.

**Comment by dain** [comment]
Couple more things that can help.  In the coordinator logs, we print debug messages about ever state change of a query.  Just grep out ever line containing the query id.  Also, on the worker machine do the same, but with the specific task id.  Also the http logs might help, but you'll need to prune out the likely huge block of gets that are keeping the task alive.
